:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:toc: macro

== Angular Deployment Demo Steps

In this demo, I'll show how to deploy an Angular + Spring Boot app to Heroku. I'll also show you how to use `ng deploy` to deploy to Firebase, Netlify, and AWS S3.

**Prerequisites:**

* https://adoptopenjdk.net/[Java 11]+
* https://nodejs.org/[Node 12]+
* https://docs.docker.com/get-docker/[Docker]
* An https://developer.okta.com/signup/[Okta Developer Account]

TIP: The brackets at the end of some steps indicate the IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

toc::[]

=== Create an Angular + Spring Boot App

. Clone the Angular + Bootstrap example app.
+
[source,shell]
----
git clone https://github.com/oktadeveloper/okta-angular-bootstrap-example.git \
okta-angular-deployment-example
----

==== Secure Your Angular + Spring Boot App with OIDC

. https://id.heroku.com/login[Log in to Heroku] and create a new app (e.g., `bootiful-angular`).

. After creating your app, click on the **Resources** tab and add the **Okta** add-on.
+
_Mention that you'll need a credit card to provision add-ons._

. Go to your app's **Settings** tab and click the **Reveal Config Vars** button.

. Create an `okta.env` file in the `notes-api` directory and copy your Oktas config vars into it, where `$OKTA_*` is the value from Heroku.
+
[source,shell]
----
export OKTA_OAUTH2_ISSUER=$OKTA_OAUTH2_ISSUER
export OKTA_OAUTH2_CLIENT_ID=$OKTA_OAUTH2_CLIENT_ID_WEB
export OKTA_OAUTH2_CLIENT_SECRET=$OKTA_OAUTH2_CLIENT_SECRET_WEB
----
+
NOTE: If you're on Windows without https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux] installed, create an `okta.bat` file and use `SET` instead of `export`.

. Start your Spring Boot app from the `notes-api` directory.
+
[source,shell]
----
source okta.env
./gradlew bootRun
----
+
TIP: Show how to configure environment variables in IDEA for `DemoApplication`.

. Configure Angular for OIDC authentication by modifying its `auth-routing.module.ts` to use the generated issuer and client ID.

. Modify the Heroku-created browser app and add `\http://localhost:4200/callback` as a **Login redirect URI** and `\http://localhost:4200` as a **Logout redirect URI**.

. Add `\http://localhost:4200` as a trusted origin in **API** > **Trusted Origins**.

. Install the Angular app's dependencies and start it.
+
[source,shell]
----
npm i
ng serve
----

. Log in to `http://localhost:4200` and show how it logs you in straight-away.

. Log out and show how you can use the credentials from Heroku's config vars to log in.

. Commit your changes to Git.
+
[source,shell]
----
git commit -am "Add Okta OIDC Configuration"
----


== Containers FTW!

⚡️ Find the code on GitHub: https://github.com/oktadeveloper/okta-angular-spring-boot-docker-example[@oktadeveloper/okta-angular-spring-boot-docker-example].

////
👀 Read the blog post: https://developer.okta.com/blog/2020/01/09/java-rest-api-showdown[Java REST API Showdown: Which is the Best Framework on the Market?].
////
