:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:toc: macro

== Angular + Bootstrap Demo Steps

In this demo, I'll show how to integrate Bootstrap into an Angular 9 app. I'll also convert the app to use Sass (because CSS is more fun with Sass), make the app look good, add form validation, and write some code to develop a searchable, sortable, and pageable data table. The last part sounds hard, but it only requires < 10 lines of code on the Spring Boot side of things. Kotlin and Spring Data JPA FTW!

// This is a demo script with the bare-bones steps you need to https://developer.okta.com/blog/2020/01/06/crud-angular-9-spring-boot-2[build a secure CRUD app with Angular 9 and Spring Boot 2.2].

NOTE: This demo starts from a previous tutorial: https://developer.okta.com/blog/2020/01/06/crud-angular-9-spring-boot-2[Build a CRUD App with Angular 9 and Spring Boot 2.2].

**Prerequisites:** https://nodejs.org/[Node 12], https://adoptopenjdk.net/[Java 11], and an https://developer.okta.com/signup/[Okta Developer Account].

TIP: The brackets at the end of some steps indicate the IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

toc::[]

=== Integrate Bootstrap with Angular 9

. Clone the Angular 9 + Spring Boot 2.2 CRUD example from my previous blog post.

  git clone https://github.com/oktadeveloper/okta-spring-boot-2-angular-9-example.git okta-angular-bootstrap-example

. Navigate into `okta-angular-bootstrap-example/notes` and `npm install`

. Add Bootstrap and NG Bootstrap

  npm i bootstrap@4.4.1 @ng-bootstrap/ng-bootstrap@6.0.0

. Add `NgbModule` to `app.module.ts`

. Run `ng serve -o`; show blank screen and error in console

. Run `ng add @angular/localize` to fix this error

. Modify `styles.css` to add a reference to Bootstrap's CSS

  @import "~bootstrap/dist/css/bootstrap.css";

. Change `app.component.html` to use Bootstrap classes

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <a class="navbar-brand text-light" href="#">{{ title }} app is running!</a>
  </nav>
  <div class="container-fluid pt-3">
   <router-outlet></router-outlet>
  </div>

. Show `http://localhost:4200` and how it's starting to look better

=== Secure Angular and Spring Boot with OpenID Connect

. Register a Web app on Okta; use `http://localhost:8080/login/oauth2/code/okta` for the redirect URI

  export OKTA_OAUTH2_ISSUER=https://{yourOktaDomain}/oauth2/default
  export OKTA_OAUTH2_CLIENT_ID={yourClientId}
  export OKTA_OAUTH2_CLIENT_SECRET={yourClientSecret}

. Start the Spring Boot app, sourcing `okta.env` first

. Register a SPA app on Okta, noting Trusted Origins

. Update `auth-routing.module.ts` with the issuer and client ID

. Show how you can log in and create notes

. You might notice the list screen isn't quite _beautiful_, yet...

. Commit your progress to GitHub

  git commit -am "Add Bootstrap and configure OIDC"

=== Use Sass to Customize Bootstrap

. Run the `ng config` in the `notes` directory to convert your project to use Sass

  ng config schematics.@schematics/angular:component.styleext scss

. Show files that end in `.css`

  find . -name "*.css" -not -path "./node_modules/*"

. Rename these files to have a `.scss` extension

  find . -name "*.css" -not -path "./node_modules/*" | rename -v "s/css/scss/g"

. Replace all references to the `.css` extension

  find ./src/app -type f -exec sed -i '' -e  's/.css/.scss/g' {} \;

. Modify `angular.json` to reference `src/styles.scss`

. Change `styles.scss` to use Bootstrap's Sass

  @import "~bootstrap/scss/bootstrap.scss";

. Show how you can override Bootstrap's default colors by creating a `_variables.scss` file

  $primary: orange;
  $secondary: blue;
  $light: lighten($primary, 20%);
  $dark: darken($secondary, 10%);

. Import it in `styles.scss` and watch the colors change

  @import "variables";

. Comment out variables and continue

=== Make Your Angular App Beautiful with Bootstrap

. Add a Navbar in `app.component.html` [`bs-navbar`]

. Remove the login and logout buttons from `home.component.html`

. Show your stylish app and unresponsive menu

. Add a click handler on the toggler and `ngbCollapse` to the menu

  <button (click)="isCollapsed = !isCollapsed" class="navbar-toggler" ...>
  <div [ngbCollapse]="isCollapsed" class="collapse navbar-collapse" ...>

. Add `isCollapsible` to `app.component.ts` and change the title to be capitalized

  title = 'Notes';
  isCollapsed = true;

. Modify the `note-list.component.html` so the breadcrumb doesn't float and all the content is in the same card

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">
      <div class="card-text">
      // form.inline-form
      // title.ml-s mr-2
      // feedback.m-2

=== Add Validation and Bootstrap to the Note Edit Template

. Click **New** to see the form needs some work

. Show how `form-group` and `form-control` are already used from https://getbootstrap.com/docs/4.4/components/forms/[Bootstrap's forms]

. Rearrange things to use the proper `card-*` classes

. Make the title field **required** [`bs-required`]

  <input [(ngModel)]="note.title" id="title" name="title" class="form-control" required
         #name="ngModel" [ngClass]="{'is-invalid': name.touched && name.invalid,  'is-valid': name.touched && name.valid}">
  <div [hidden]="name.valid" style="display: block" class="invalid-feedback">
    Title is required
  </div>

. Show how the title is required and losing focus highlights the field

=== Add a Searchable, Sortable, and Pageable Data Table with Angular and Spring Data JPA

. Change `UserController#notes()` so it accepts a title parameter

  fun notes(principal: Principal, title: String?): List<Note> {
      println("Fetching notes for user: ${principal.name}")
      return if (title.isNullOrEmpty()) {
          repository.findAllByUser(principal.name)
      } else {
          println("Searching for title: ${title}")
          repository.findAllByUserAndTitleContainingIgnoreCase(principal.name, title)
      }
  }

. Add a new `findAllByUserAndTitleContainingIgnoreCase()` method to `NotesRepository`

. Restart your server and show how you can search for notes by title

=== Add Sort Functionality with Angular and Bootstrap

. Create a `sortable.directive.ts` [`bs-sortable`]

. Add `SortableHeaderDirective` as a declaration in `note.module.ts`

. Add a `headers` variable to `notes-list.component.ts` and an `onSort()` method [`bs-sort`]

  @ViewChildren(SortableHeaderDirective) headers: QueryList<SortableHeaderDirective>;
  ..
  onSort({column, direction}: SortEvent) {
    // reset other headers
    this.headers.forEach(header => {
      if (header.sortable !== column) {
        header.direction = '';
      }
    });
    this.filter.column = column;
    this.filter.direction = direction;
    this.search();
  }

. Update the `note-filter.ts` to have `column` and `direction` properties

. Modify the `find()` method in `NoteService` to pass a `sort` parameter when appropriate [`bs-find`]

  find(filter: NoteFilter): Observable<Note[]> {
    const params: any = {
      title: filter.title,
      sort: `${filter.column},${filter.direction}`,
    };
    if (!filter.direction) { delete params.sort; }
    const userNotes = 'http://localhost:8080/user/notes';
    return this.http.get(userNotes, {params, headers}).pipe(
      map((response: any) => {
        return response.content;
      })
    );
  }

. Update `note-list.component.html` so it uses the `sortable` directive and calls `onSort()`

  <th class="border-top-0" scope="col" sortable="title" (sort)="onSort($event)">Title</th>
  <th class="border-top-0" scope="col" sortable="text" (sort)="onSort($event)">Text</th>

. Add CSS in `styles.scss` to show a sort indicator [`bs-css-sort`]

=== Add Sorting and Paging in Spring Boot with Spring Data JPA

. https://docs.spring.io/spring-data/rest/docs/current/reference/html/#pagibs-and-sorting[Spring Data has excellent support for paging and sorting]

. Add a `Pageable` argument to `UserController#notes()`, add `pageable` as an argument, and return `Page` instead of `List`

. Modify `NotesRepository` to add a `Pageable` argument to its methods and return a `Page`

. Update `DataInitializer` to create a thousand notes for your user

  for (x in 0..1000) {
    repository.save(Note(title = "Note ${x}", user = "<your username>"))
  }

. Restart Spring Boot, click on the **Title** column to see sorting in action!

=== Add Pagination with Angular and Bootstrap

. Use https://bs-bootstrap.github.io/#/components/pagination/overview[NG Bootstrap's `ngb-pagination`] to add pagination in Angular

. Add `page` and `size` variables to `note-filter.ts`

  page = 0;
  size = 20;

. Just after `</table>` in `note-list.component.html`, add a pagination component and page size selector [`bs-pagination`]

. Add `NgbModule` as an import to `note.module.ts`

. In `note-list.component.ts`, add a `total$` observable and set it from the `search()` method

  total$: Observable<number>;
  search(): void {
    this.noteService.load(this.filter);
    this.total$ = this.noteService.size$;
  }

. Add `onPageChange()`, `onChange()` method, and modify `onSort()` to set the page to 0 [`bs-change`]

. Update `notes.service.ts` to add a `size$` observable and parameters for the page size and page number

  size$ = new BehaviorSubject<number>(0);
  ...
  find(filter: NoteFilter): Observable<Note[]> {
    const params: any = {
      ...
      size: filter.size,
      page: filter.page
    };
    ...
    return this.http.get(userNotes, {params, headers}).pipe(
      map((response: any) => {
        this.size$.next(response.totalElements);
        return response.content;
      })
    );
  }

. Show how the note list now has a working pagination feature

. Rejoice! 🎉

== Angular with Bootstrap + Spring Boot is Powerful

😎 Find the code on GitHub: https://github.com/oktadeveloper/okta-angular-bootstrap-example[@oktadeveloper/okta-angular-bootstrap-example]

You can develop the same app (a notes CRUD app that uses Angular, Bootstrap, Spring Boot, and Kotlin) in 3 steps with KHipster!

. Install JHipster and its Kotlin Blueprint

  npm install -g generator-jhipster@6.6.0 generator-jhipster-kotlin@1.4.0

. Create an `easy-notes` directory and a `notes.jdl` file in it

  application {
    config {
      baseName notes
      authenticationType oauth2
      buildTool gradle
      searchEngine elasticsearch
      testFrameworks [protractor]
    }
    entities *
  }
  entity Note {
    title String required
    text TextBlob
  }
  relationship ManyToOne {
    Note{user(login)} to User
  }
  paginate Note with pagination

. Create your app

  khipster import-jdl notes.jdl

That's it! 🎉

. Start Keycloak, Elasticsearch, and your app

  killall java
  docker-compose -f src/main/docker/keycloak.yml up -d
  docker-compose -f src/main/docker/elasticsearch.yml up -d
  ./gradlew

. Run `npm run e2e` to verify everything works

. Show search and form with validation at `http://localhost:8080`

. Show how to https://www.jhipster.tech/security/#okta[make JHipster work with Okta]

  source ~/.okta.env
  ./gradlew


