:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:toc: macro

== Angular Deployment Demo Steps

In this demo, I'll show how to deploy an Angular + Spring Boot app to Heroku. I'll also show you how to use `ng deploy` to deploy to Firebase, Netlify, and AWS S3.

**Prerequisites:**

* https://adoptopenjdk.net/[Java 11]+
* https://nodejs.org/[Node 12]+
* https://docs.docker.com/get-docker/[Docker]
* An https://developer.okta.com/signup/[Okta Developer Account]

TIP: The brackets at the end of some steps indicate the IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

toc::[]

=== Create an Angular + Spring Boot App

. Clone the Angular + Bootstrap example app.
+
[source,shell]
----
git clone https://github.com/oktadeveloper/okta-angular-bootstrap-example.git \
okta-angular-deployment-example
----

==== Secure Your Angular + Spring Boot App with OIDC

. https://id.heroku.com/login[Log in to Heroku] and create a new app (e.g., `bootiful-angular`).

. After creating your app, click on the **Resources** tab and add the **Okta** add-on.
+
_Mention that you'll need a credit card to provision add-ons._

. Go to your app's **Settings** tab and click the **Reveal Config Vars** button.

. Create an `okta.env` file in the `notes-api` directory and copy your Oktas config vars into it, where `$OKTA_*` is the value from Heroku.
+
[source,shell]
----
export OKTA_OAUTH2_ISSUER=$OKTA_OAUTH2_ISSUER
export OKTA_OAUTH2_CLIENT_ID=$OKTA_OAUTH2_CLIENT_ID_WEB
export OKTA_OAUTH2_CLIENT_SECRET=$OKTA_OAUTH2_CLIENT_SECRET_WEB
----
+
NOTE: If you're on Windows without https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux] installed, create an `okta.bat` file and use `SET` instead of `export`.

. Start your Spring Boot app from the `notes-api` directory.
+
[source,shell]
----
source okta.env
./gradlew bootRun
----
+
TIP: Show how to configure environment variables in IDEA for `DemoApplication`.

. Configure Angular for OIDC authentication by modifying its `auth-routing.module.ts` to use the generated issuer and client ID.

. Modify the Heroku-created browser app and add `\http://localhost:4200/callback` as a **Login redirect URI** and `\http://localhost:4200` as a **Logout redirect URI**.

. Add `\http://localhost:4200` as a trusted origin in **API** > **Trusted Origins**.

. Install the Angular app's dependencies and start it.
+
[source,shell]
----
npm i
ng serve
----

. Log in to `http://localhost:4200` and show how it logs you in straight-away.

. Log out and show how you can use the credentials from Heroku's config vars to log in.

. Commit your changes to Git.
+
[source,shell]
----
git commit -am "Add Okta OIDC Configuration"
----

=== Prepare Angular + Spring Boot for Production

In this section, you'll update to the latest releases, configure production URLs, and configure PostgreSQL for production.

. Configure Gradle's https://github.com/patrikerdes/gradle-use-latest-versions-plugin[Use Latest Versions Plugin] by adding the following to the `plugins` block at the top of `notes-api/build.gradle.kts`.
+
[source,kotlin]
----
plugins {
    id("se.patrikerdes.use-latest-versions") version "0.2.13"
    id("com.github.ben-manes.versions") version "0.28.0"
    ...
}
----

. For compatibility with Spring Boot 2.3, you'll need to update the Gradle Wrapper to use Gradle 6.3+.
+
[source,shell]
----
./gradlew wrapper --gradle-version=6.4 --distribution-type=bin
----

. Upgrade to the latest versions in the `notes-api` directory.
+
[source,shell]
----
./gradlew useLatestVersions
----

. Verify everything works by re-starting Spring Boot and going to `http://localhost:8080/api/notes`.

. For Angular, use https://www.npmjs.com/package/npm-check-updates[npm-check-updates] to upgrade npm dependencies.
+
[source,shell]
----
npm i -g npm-check-updates
ncu -u
----

. Change the TypeScript version in `package.json` to match Angular's expected version.
+
[source,json]
----
"typescript": "~3.8.3"
----

. Then run the following commands in the `notes` directory:
+
[source,shell]
----
npm i
npm audit fix
ng serve
----

. Confirm you can still log in at `http://localhost:4200`.

. Commit all your changes to source control.
+
[source,shell]
----
git commit -am "Update dependencies to latest versions"
----

==== Configure Production URLs

There are a few places where `localhost` is hard-coded:

1. `notes-api/src/main/kotlin/.../DemoApplication.kt` has `\http://localhost:4200`
2. `notes/src/app/shared/okta/auth-interceptor.ts` has `\http://localhost`
3. `notes/src/app/note/note.service.ts` has `\http://localhost:8080`

You need to change Spring Boot's code so other origins can make CORS requests too.

. Open `DemoApplication.kt` and change the `simpleCorsFilter` bean so it configures the allowed origins from your Spring environment.
+
[source,kotlin]
----
@SpringBootApplication
class DemoApplication {

    @Value("#{ @environment['allowed.origins'] ?: {} }")
    private lateinit var allowedOrigins: List<String>

    @Bean
    fun simpleCorsFilter(): FilterRegistrationBean<CorsFilter> {
        val source = UrlBasedCorsConfigurationSource()
        val config = CorsConfiguration()
        config.allowCredentials = true
        config.allowedOrigins = allowedOrigins
        config.allowedMethods = listOf("*");
        config.allowedHeaders = listOf("*")
        source.registerCorsConfiguration("/**", config)
        val bean = FilterRegistrationBean(CorsFilter(source))
        bean.order = Ordered.HIGHEST_PRECEDENCE
        return bean
    }
}
----

. Define the `allowed.origins` property in `application.properties`.
+
[source,properties]
----
allowed.origins=http://localhost:4200
----

. Open `environment.ts` and add an `apiUrl` variable for development.
+
[source,typescript]
----
export const environment = {
  production: false,
  apiUrl: 'http://localhost:8080'
};
----

. Edit `environment.prod.ts` to point to your production Heroku URL.
+
[source,typescript]
----
export const environment = {
  production: true,
  apiUrl: 'https://bootiful-angular.herokuapp.com'
};
----

. Update `auth-interceptor.ts` to use `environment.apiUrl`.
+
[source,typescript]
----
private async handleAccess(request: HttpRequest<any>, next: HttpHandler): Promise<HttpEvent<any>> {
    const allowedOrigins = [environment.apiUrl];
    ...
}
----

. Update `notes.service.ts` as well.
+
[source,typescript]
----
export class NoteService {
  ...
  api = `${environment.apiUrl}/api/notes`;
  ...

  find(filter: NoteFilter): Observable<Note[]> {
    ...

    const userNotes = `${environment.apiUrl}/user/notes`;
    ...
  }
}
----

. Edit `build.gradle.kts` and change the H2 dependency so PostgreSQL is used when `-Pprod` is passed in.
+
[source,kotlin]
----
if (project.hasProperty("prod")) {
    runtimeOnly("org.postgresql:postgresql")
} else {
    runtimeOnly("com.h2database:h2")
}
----

. Add the following code to make the `prod` profile the default when `-Pprod` is included in Gradle commands.
+
[source,kotlin]
----
val profile = if (project.hasProperty("prod")) "prod" else "dev"

tasks.bootRun {
    args("--spring.profiles.active=${profile}")
}

tasks.processResources {
    rename("application-${profile}.properties", "application.properties")
}
----

. Rename `application.properties` to `application-dev.properties` and add a URL for H2 so it will persist to disk.
+
[source,properties]
----
allowed.origins=http://localhost:4200
spring.datasource.url=jdbc:h2:file:./build/h2db/notes;DB_CLOSE_DELAY=-1
----

. Create a `src/main/docker/postgresql.yml` to test your `prod` profile settings.
+
[source,yaml]
----
version: '2'
services:
  notes-postgresql:
    image: postgres:12.1
    environment:
      - POSTGRES_USER=notes
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
----

. Create an `application-prod.properties` with PostgeSQL settings.
+
[source,properties]
----
allowed.origins=http://localhost:4200
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/notes
spring.datasource.username=notes
spring.datasource.password=
----

. The word `user` is a keyword in PostgreSQL, so you'll need to change `user` to `username` in the `Note` entity.

. Add a `@Profile` annotation to the top of `DataInitializer` so it only runs for the `dev` profile.
+
[source,kotlin]
----
@Profile("dev")
class DataInitializer(val repository: NotesRepository) : ApplicationRunner {...}
----

. To test your profiles, start PostgreSQL using Docker Compose.
+
[source,shell]
----
docker-compose -f src/main/docker/postgresql.yml up
----

. In another terminal, run your Spring Boot app.
+
[source,shell]
----
source okta.env
./gradlew bootRun -Pprod
----

. Confirm your Angular app can talk to it and get ready to deploy to production!
+
[source,shell]
----
git commit -am "Configure environments for production"
----

=== Deploy Spring Boot to Heroku

. Install the https://devcenter.heroku.com/articles/heroku-cli[Heroku CLI].
+
[source,shell]
----
brew tap heroku/brew && brew install heroku
----

. Mention how Heroku expects one Git repo per application and that https://elements.heroku.com/buildpacks/lstoll/heroku-buildpack-monorepo[heroku-buildpack-monorepo] solves this.

. Associate your existing Git repo with the app on Heroku.
+
[source,shell]
----
heroku git:remote -a $APP_NAME
----

. Set the `APP_BASE` config variable to point to the `notes-api` directory. While you're there, add the monorepo and Gradle buildpacks.
+
[source,shell]
----
heroku config:set APP_BASE=notes-api
heroku buildpacks:add https://github.com/lstoll/heroku-buildpack-monorepo
heroku buildpacks:add heroku/gradle
----

. Attach a PostgreSQL database to your app.
+
[source,shell]
----
heroku addons:create heroku-postgresql
----

. By default, https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku[Heroku's Gradle support] runs `./gradlew build -x test`. Since you want it to run `./gradlew bootJar -Pprod`, you'll need to override it by setting a `GRADLE_TASK` config var.
+
[source,shell]
----
heroku config:set GRADLE_TASK="bootJar -Pprod"
----

. Run the following command and remove `_WEB` from the two variables that have it.
+
[source,shell]
----
heroku config:edit
----

. Now you're ready to deploy! Take a deep breath and witness how Heroku can deploy your Spring Boot + Kotlin app with a simple `git push`.
+
[source,shell]
----
git push heroku master
----

. Run `heroku open` and log in.

. Add a `HomeController` [`kotlin-home`]
+
[source,kotlin]
----
package com.okta.developer.notes

import org.springframework.security.core.annotation.AuthenticationPrincipal
import org.springframework.security.oauth2.core.oidc.user.OidcUser
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RestController

@RestController
class HomeController {

    @GetMapping("/")
    fun hello(@AuthenticationPrincipal user: OidcUser): String {
        return "Hello, ${user.fullName}"
    }
}
----

. Commit this change and deploy it to Heroku.
+
[source,shell]
----
git commit -am "Add HomeController"
git push heroku master
----

. Show `HomeController` workin on Heroku.

=== Deploy Angular to Heroku

. Create another app on Heroku for the Angular frontend.
+
[source,shell]
----
heroku create
----

. Set the `APP_BASE` config variable and add the necessary buildpacks.
+
[source,shell]
----
APP_NAME=<app-name-from-heroku-create>
heroku config:set APP_BASE=notes -a $APP_NAME
heroku buildpacks:add https://github.com/lstoll/heroku-buildpack-monorepo -a $APP_NAME
heroku buildpacks:add heroku/nodejs -a $APP_NAME
----

. Change `notes/package.json` to have a different `start` script.
+
[source,json]
----
"start": "http-server-spa dist/notes index.html $PORT",
----

. Add a `heroku-postbuild` script to your `package.json`:
+
[source,json]
----
"heroku-postbuild": "ng build --prod && npm install -g http-server-spa"
----

. Commit your changes, add a new Git remote for this app, and deploy!
+
[source,shell]
----
git commit -am "Prepare Angular for Heroku"
git remote add angular https://git.heroku.com/<your-app-name>.git
git push angular master
----

. When it finishes deploying, you can open your Angular app with:
+
[source,shell]
----
heroku open --remote angular
----

. You won't be able to log in to your app until you modify its Login redirect URI on Okta.

  * **Login redirect URI**: `\https://<angular-app-on-heroku>.herokuapp.com/callback`
  * **Logout redirect URI**:  `\https://<angular-app-on-heroku>.herokuapp.com`

. You should be able to log in now, but you won't be able to add any notes. Add an `ALLOWED_ORIGINS` variable in your Spring Boot app.
+
[source,shell]
----
heroku config:set ALLOWED_ORIGINS=https://<angular-app-on-heroku>.herokuapp.com --remote heroku
----

. Now you should be able to add a note. Pat yourself on the back for a job well done!

. Change Hibernate to validate your schema by overriding the `ddl-auto` value.
+
[source,shell]
----
heroku config:set SPRING_JPA_HIBERNATE_DDL_AUTO=validate --remote heroku
----

==== Make Your Angular App More Secure on Heroku

. Show how accessing the using `http` (instead of `https`) doesn't work.

. Show security headers score using https://securityheaders.com[securityheaders.com].

. Create a `notes/static.json` file with the configuration for secure headers and redirect all HTTP requests to HTTPS.
+
[source,json]
----
{
  "headers": {
    "/**": {
      "Content-Security-Policy": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'none'",
      "Referrer-Policy": "no-referrer, strict-origin-when-cross-origin",
      "Strict-Transport-Security": "max-age=63072000; includeSubDomains",
      "X-Content-Type-Options": "nosniff",
      "X-Frame-Options": "DENY",
      "X-XSS-Protection": "1; mode=block",
      "Feature-Policy": "accelerometer 'none'; camera 'none'; microphone 'none'"
    }
  },
  "https_only": true,
  "root": "dist/notes/",
  "routes": {
    "/**": "index.html"
  }
}
----

. For `static.json` to be read, you have to use the https://github.com/heroku/heroku-buildpack-static[Heroku static buildpack]. This buildpack is made for SPA applications, so you can change the `scripts` section to Angular defaults.
+
[source,json]
----
"scripts": {
  "ng": "ng",
  "start": "ng serve",
  "build": "ng build",
  "test": "ng test",
  "lint": "ng lint",
  "e2e": "ng e2e"
},
----

. Commit your changes to Git, add the static buildpack, and redeploy your Angular app.
+
[source,shell]
----
git add static.json
git commit -am "Configure secure headers and static buildpack"
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-static.git --remote angular
git push angular master
----

. Now you should have a security report you can be proud of! 😃

=== Angular Deployment with `ng deploy`

In Angular CLI v8.3.0, an `ng deploy` command was introduced that allows you to automate deploying to many different cloud providers.

==== Angular Deployment to Firebase

. Create a `firebase` branch so you can make changes without affecting the work you've done for Heroku deployments.
+
[source,shell]
----
git checkout -b firebase
----

. Open a browser and go to https://firebase.google.com/[firebase.google.com]. Log in to your account, go to the console, and create a new project.
. Install the `@angular/fire` package.
+
[source,shell]
----
ng add @angular/fire
----

. Now you can run `ng deploy` and everything should work.

. You'll need to add the project's URL as an allowed origin in your Spring Boot app on Heroku. Copy the printed `Hosting URL` value and run the following command.
+
[source,shell]
----
heroku config:edit --remote heroku
----

. Add the new URL after your existing Heroku one, separating them with a comma. For example:
+
[source,shell]
----
ALLOWED_ORIGINS='https://stark-lake-39546.herokuapp.com,https://ng-notes-1337.web.app'
----

. You'll also need to modify your Okta SPA app to add your Firebase URL as a Login redirect URI and Logout redirect URI. For example:

  - **Login redirect URI**: `\https://ng-notes-1337.web.app/callback`
  - **Logout redirect URI**: `\https://ng-notes-1337.web.app`

==== Strong Security Headers on Firebase

. Test Firebase site on https://securityheaders.com/[securityheaders.com] to show how it scores a **D**.

. To fix this, you can https://firebase.google.com/docs/hosting/full-config#headers[configure headers] in your `firebase.json` file.
+
[source,json]
----
"headers": [ {
  "source": "/**",
  "headers": [
    {
      "key": "Content-Security-Policy",
      "value": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'none'"
    },
    {
      "key": "Referrer-Policy",
      "value": "no-referrer, strict-origin-when-cross-origin"
    },
    {
      "key": "X-Content-Type-Options",
      "value": "nosniff"
    },
    {
      "key": "X-Frame-Options",
      "value": "DENY"
    },
    {
      "key": "X-XSS-Protection",
      "value": "1; mode=block"
    },
    {
      "key": "Feature-Policy",
      "value": "accelerometer 'none'; camera 'none'; microphone 'none'"
    }
  ]
} ]
----
+
NOTE: You don't need to include a `Strict-Transport-Security` header because Firebase includes it by default.

. Run `ng deploy` and you should get an **A** now!

. Commit your changes to the `firebase` branch.
+
[source,shell]
----
git commit -am "Add Firebase deployment"
----

==== Angular Deployment to Netlify

. Check out your `master` branch and create a new `netlify` one.
+
[source,shell]
----
git checkout master
git checkout -b netlify
----

. Before running the command to add Netlify support, you'll need to https://app.netlify.com/signup[create a Netlify account].

. Create a temporary directory with an `index.html` file in it. Put "Hello, World" in the HTML file, then drag the directory into your browser window.

. Click on **Site Settings** to copy your **API ID** to a text editor. You'll also need a personal access token. To create one, click on your avatar in the top right > **User settings** > **Applications** and click **New access token**. Copy the generated token to your text editor.

. Run the command below to add Netlify deployment support.
+
[source,shell]
----
ng add @netlify-builder/deploy
----

. Copy and paste your API ID and personal access token when prompted, then run `ng deploy` to deploy your site.

. Update your Spring Boot app on Heroku to allow your Netlify app URL:
+
[source,shell]
----
heroku config:edit --remote heroku
----

. Update your Okta app to whitelist the URL as login and logout redirects.

. Show login and how redirect back to your app results in a 404.

. This happens because Netlify doesn't know your app is a SPA that manages its own routes. To fix this, create a `_redirects` file in the `notes/src` directory with the following contents.
+
[source,shell]
----
/*    /index.html   200
----

. Modify `angular.json` to include this file in its assets.
+
[source,json]
----
"assets": [
  "src/_redirects",
  "src/favicon.ico",
  "src/assets"
],
----

. Run `ng deploy` again and you should be able to log in successfully.

==== Better Security Headers on Netlify

If you test your new Firebase site on https://securityheaders.com/[securityheaders.com], you'll score a **D**. Netlify allows you to add https://docs.netlify.com/routing/headers/[custom headers] to improve your score.

. Create a `src/_headers` file with the following contents.
+
[source,text]
----
/*
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'none'
  Referrer-Policy: no-referrer, strict-origin-when-cross-origin
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  Feature-Policy: accelerometer 'none'; camera 'none'; microphone 'none'
----
+
NOTE: You don't need to include a `Strict-Transport-Security` header because Netlify includes one by default.

. Modify `angular.json` to include this file in its assets.
+
[source,json]
----
"assets": [
 "src/_headers",
 "src/_redirects",
 "src/favicon.ico",
 "src/assets"
],
----

. Run `ng deploy` and you should get an **A** now!

. Commit your changes to the `netlify` branch.
+
[source,shell]
----
git commit -am "Add Netlify deployment"
----

[WARNING]
====
The Netlify schematic writes your access token to `angular.json`, which is a security risk (if you push these changes to your source control system).

[source,json]
----
"deploy": {
 "builder": "@netlify-builder/deploy:deploy",
 "options": {
   "outputPath": "dist/notes",
   "netlifyToken": "04b966f772XXX...",
   "siteId": "1dda959c-XXXX..."
 }
}
----
====

==== Angular Deployment to AWS S3

Amazon Simple Storage Service (Amazon S3) is an object storage service that is a popular option for hosting static sites.

. Check out your `master` branch and create a new `aws` one.
+
[source,shell]
----
git checkout master
git checkout -b aws
----

. Before running the command to add S3 deployment support, you'll need a few things:

  - An S3 Bucket
  - An AWS Region Name
  - A Secret Access Key
  - An Access Key ID

. After https://portal.aws.amazon.com/billing/signup[creating an account], go to the https://s3.console.aws.amazon.com/[Amazon S3 console]. Click **Create Bucket** and give it a name you'll remember. Use the default region selected for you and click **Create Bucket**.

. To create the secret access key, go to your https://console.aws.amazon.com/iam/home?nc2=h_m_sc#/security_credentials[security credentials page]. Expand the **Access keys** section, and then **Create New Access Key**. Click **Show Access Key** and copy the values into a text editor.

. Add the `@jefiozie/ngx-aws-deploy` package to deploy to S3:
+
[source,shell]
----
ng add @jefiozie/ngx-aws-deploy
----
+
When prompted, enter your region, bucket name, access key, and access key ID. When prompted for the folder, leave it blank.
+
CAUTION: This process writes these raw values to your `angular.json`. For a more secure setup, use environment variables: `NG_DEPLOY_AWS_ACCESS_KEY_ID`, `NG_DEPLOY_AWS_SECRET_ACCESS_KEY`, `NG_DEPLOY_AWS_BUCKET` and `NG_DEPLOY_AWS_REGION`.

. Run `ng deploy`.

. Next, you need to configure S3 for static website hosting. Go to your bucket > **Properties** > **Static website hosting**. Take note of the endpoint URL at the top of the card, you'll need this in a minute.

. Type `index.html` for the index and error document and click **Save**.

. By default, Amazon S3 blocks public access to your buckets. Go to the **Permissions** tab. Click the **Edit** button, clear **Block all public access**, and click **Save**.

. The last step you need to do to make it public is add a bucket policy. Go to **Permissions** > **Bucket Policy** and paste the following into the editor, replacing `{your-bucket-name}` with your bucket's name.
+
[source,json]
----
{
   "Version": "2012-10-17",
   "Statement": [
       {
           "Sid": "PublicReadGetObject",
           "Effect": "Allow",
           "Principal": "*",
           "Action": [
               "s3:GetObject"
           ],
           "Resource": [
               "arn:aws:s3:::{your-bucket-name}/*"
           ]
       }
   ]
}
----

. At this point, you could navigate to `\https://<bucket-name>.s3.amazonaws.com/index.html` in your browser, and the application will load. However, there's no HTTP to HTTPS redirect or resolution of `index.html` by default. You can use CloudFront to solve these issues.

. Open the https://console.aws.amazon.com/cloudfront/[CloudFront console] and choose **Create Distribution**. Under the Web section, click the **Get Started** button. Click in the **Origin Domain Name** field and select your S3 bucket.

. Set the **Viewer Protocol Policy** to `Redirect HTTP to HTTPS`, allow all HTTP methods, and enter `index.html` as the **Default Root Object**. Scroll to the bottom and click **Create Distribution**. When the Status column changes from `In Progress` to `Deployed`, navigate to the domain name in your browser.
+
NOTE: A distribution can take 20 minutes to deploy.

. After your distribution is deployed, update your Spring Boot app on Heroku to allow your CloudFront URL:
+
[source,shell]
----
heroku config:edit --remote heroku
----

. Update your Okta SPA app to whitelist the URL as a redirect, too.

. If you try to log in, you'll get a 403 when redirecting back to the site. To fix this, edit your distribution > **Error pages**. Create two custom error responses for `404` and `403`. Return a path of `/index.html` and a `200: OK` response code.

. Now you should be able to authenticate to your Angular app on AWS successfully!

==== Awesome Security Headers with AWS CloudFront + S3

. Show test results on https://securityheaders.com/[securityheaders.com].

. To add custom headers to AWS, you can use https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/[Lambda@Edge to add security headers].

. Go to the https://us-west-2.console.aws.amazon.com/lambda/home[Lambda Console] and select the `US-East-1 N` region from a drop-down list in the top right. Click **Create Function** to create a new function.

. Choose **Author from scratch** and name it `securityHeaders`. Under Permissions, select **Create a new role from AWS Policy templates**. Name the role `securityHeaders-role` and select **Basic Lambda@Edge permissions (for CloudFront trigger)**. Click **Create function**.

. In the Function code section, set `index.js` to have the following JavaScript.
+
[source,js]
----
exports.handler = (event, context, callback) => {

  // get response
  const response = event.Records[0].cf.response;
  const headers = response.headers;

  // set headers
  headers['content-security-policy'] = [{key: 'Content-Security-Policy', value: "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'none'"}];
  headers['referrer-policy'] = [{key: 'Referrer-Policy', value: 'no-referrer, strict-origin-when-cross-origin'}];
  headers['strict-transport-security'] = [{key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubdomains'}];
  headers['x-content-type-options'] = [{key: 'X-Content-Type-Options', value: 'nosniff'}];
  headers['x-frame-options'] = [{key: 'X-Frame-Options', value: 'DENY'}];
  headers['x-xss-protection'] = [{key: 'X-XSS-Protection', value: '1; mode=block'}];
  headers['feature-policy'] = [{key: 'Feature-Policy', value: "accelerometer 'none'; camera 'none'; microphone 'none'"}];

  // return modified response
  callback(null, response);
};
----

. Click **Save** and add a trigger. Select **CloudFront** and **Deploy to Lambda@Edge**. For the distribution, use the ID of your CloudFront distribution. Set the event to be **Origin response**. Select the "I acknowledge..." checkbox and click **Deploy**.

. Go back to your CloudFront Console and wait for the deploy to complete.

. Try your CloudFront domain again on https://securityheaders.com[securityheaders.com]. You should get an **A** this time.

. Commit your changes to the `aws` branch.
+
[source,shell]
----
git commit -am "Add AWS S3 deployment"
----

CAUTION: If you committed the changes in your `angular.json` file, you should delete your access key in **My Account** > **Security Credentials** and change your account password.

== Angular is Awesome!

⚡️ Find the code on GitHub: https://github.com/oktadeveloper/okta-angular-deployment-example[@oktadeveloper/okta-angular-deployment-example].

////
👀 Read the blog post: https://developer.okta.com/blog/2020/01/09/java-rest-api-showdown[Java REST API Showdown: Which is the Best Framework on the Market?].
////
